Repository Sharonina/DEV002-social-network, pull requests merged in 2022-12, with the labels that each got.

#2 Añadí lo que avanzamos para el README
  README.md
Labels: documentation

#9 Nueva rama
  README.md
Labels: documentation

#10 Pullrequest de prueba
  README.md
Labels: documentation

#11 Añadi una descripcion a README
  README.md
Labels: documentation

#20 Unión de la construcción de SPA
  .eslintrc
  assets/close.png
  assets/dog-iniciosesion.png
  assets/exclamation.png
  assets/heart.png
  assets/heart_arrow.png
  assets/heart_bco.png
  assets/heart_rosa.png
  assets/mail.png
  assets/match_flame.png
  assets/picture_gray.png
  assets/picture_purple.png
  assets/place.png
  assets/search_icon.png
  assets/tindog_logo.png
  assets/tindog_logo_b.png
  assets/tindog_logo_r.png
  package.json
  src/index.html
  src/index.js
  src/lib/index.js
  src/main.js
  src/pages/Bienvenida.js
  src/pages/Error404.js
  src/pages/RegistroUsuario.js
  src/routes/index.js
  src/styles/styles.css
  src/templates/Header.js
  src/utils/getPathName.js
  src/utils/resolveRoutes.js
  test/index.spec.js
  thumb.png
Labels: documentation, enhancement

#21 Registro usuario
  src/index.html
  src/pages/FormularioRegistroMascota.js
  src/pages/RegistroUsuario.js
  src/utils/resolveRoutes.js
Labels: enhancement

#22 Añadiendo estilos a pantalla de bienvenida
  src/assets/close.png
  src/assets/dog-iniciosesion.png
  src/assets/exclamation.png
  src/assets/heart.png
  src/assets/heart_arrow.png
  src/assets/heart_bco.png
  src/assets/heart_rosa.png
  src/assets/mail.png
  src/assets/match_flame.png
  src/assets/picture_gray.png
  src/assets/picture_purple.png
  src/assets/place.png
  src/assets/search_icon.png
  src/assets/tindog_logo.png
  src/assets/tindog_logo_b.png
  src/assets/tindog_logo_r.png
  src/index.html
  src/pages/Bienvenida.js
  src/styles/styles.css
Labels: Styles

#23 Añadiendo responsive a bienvenida y pantalla de loading
  src/index.html
  src/pages/Bienvenida.js
  src/styles/styles.css
Labels: Styles

#24 Separando funciones de lógica
  src/index.js
  src/logic/registroUsuarioLogica.js
  src/pages/Bienvenida.js
  src/pages/RegistroUsuario.js
  src/routes/index.js
Labels: enhancement

#25 agregar estilos a pagina registro-usuario y iniciar-sesion
  src/assets/logo-google.png
  src/logic/inicioSesionLogica.js
  src/pages/InicioSesion.js
  src/pages/RegistroUsuario.js
  src/styles/styles.css
  src/utils/resolveRoutes.js
Labels: Styles

#26 Configurando Firebase y agregando path a gitignore
  .gitignore
  src/firebase/configuracionFirebase.js
  src/firebase/firebaseConfig.js
Labels: enhancement

#27 Añadimos código para el manejo de errores en la pagina de registro
  src/firebase/configuracionFirebase.js
  src/firebase/firebaseConfig.js
  src/index.js
  src/logic/registroUsuarioLogica.js
  src/pages/RegistroUsuario.js
  src/styles/styles.css
Labels: enhancement

#34 La venganza de los estilos
  src/pages/Error404.js
  src/pages/FormularioRegistroMascota.js
  src/pages/InicioSesion.js
  src/pages/RegistroUsuario.js
  src/styles/styles.css
Labels: Styles

#35 La venganza de los estilos
  src/index.html
  src/logic/registroUsuarioLogica.js
  src/pages/RegistroUsuario.js
Labels: Resolved bug

#37 Cambios de boton por input + estilos
  src/logic/registroUsuarioLogica.js
  src/pages/InicioSesion.js
  src/pages/RegistroUsuario.js
  src/styles/styles.css
Labels: Styles, Bugs, HTML

#49 Registro con Google + Inicio de sesión con correo y Google
  src/logic/inicioSesionLogica.js
  src/logic/registroUsuarioLogica.js
  src/pages/Home.js
  src/pages/InicioSesion.js
  src/styles/styles.css
  src/utils/resolveRoutes.js
Labels: documentation
